name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Semantic release needs full history
        persist-credentials: false # Use GITHUB_TOKEN for release

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm run test

    - name: Run linting
      run: pnpm run check:fix

    - name: Build library
      run: pnpm run build:lib

    - name: Configure npm authentication
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

    - name: Semantic Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release

    - name: Upload release artifacts
      if: steps.semantic-release.outputs.new-release-published == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: release-artifacts
        path: |
          dist/
          package.json
          CHANGELOG.md
        retention-days: 30